# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_arm_with_base_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_with_base_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    dual_arms_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    updown_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - leftarmbase
      - leftjoint1
      - leftjoint2
      - leftjoint3
      - leftjoint4
      - leftjoint5
    command_interfaces:
      - position
    state_interfaces:
      - position

right_arm_controller:
  ros__parameters:
    joints:
      - rightarmbase
      - rightjoint1
      - rightjoint2
      - rightjoint3
      - rightjoint4
    command_interfaces:
      - position
    state_interfaces:
      - position

left_arm_with_base_controller:
  ros__parameters:
    joints:
      - updown
      - leftarmbase
      - leftjoint1
      - leftjoint2
      - leftjoint3
      - leftjoint4
      - leftjoint5
    command_interfaces:
      - position
    state_interfaces:
      - position

right_arm_with_base_controller:
  ros__parameters:
    joints:
      - updown
      - rightarmbase
      - rightjoint1
      - rightjoint2
      - rightjoint3
      - rightjoint4
    command_interfaces:
      - position
    state_interfaces:
      - position

dual_arms_controller:
  ros__parameters:
    joints:
      - updown
      - leftarmbase
      - leftjoint1
      - leftjoint2
      - leftjoint3
      - leftjoint4
      - leftjoint5
      - rightarmbase
      - rightjoint1
      - rightjoint2
      - rightjoint3
      - rightjoint4
    command_interfaces:
      - position
    state_interfaces:
      - position

updown_controller:
  ros__parameters:
    joints:
      - updown
    command_interfaces:
      - position
    state_interfaces:
      - position
