int32 left_box_id
int32 right_box_id
string snapshot_path
bool left_top_suction
bool right_top_suction
bool use_explicit_targets
geometry_msgs/PoseStamped left_target
geometry_msgs/PoseStamped right_target
robot_motion_internal_interfaces/DualGraspStrategy strategy
bool update_runtime_config
float64 box_front_x
float64 scene_y_shift
string extract_rollout_mode
bool loaded_lateral_shift_enabled
int32 extract_box_pose_rrt_max_iterations
bool use_explicit_start_state
sensor_msgs/JointState start_state
---
bool success
string message
