# 实机 CAN 控制专用 - current joint list placeholder.

controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

forward_position_controller:
  ros__parameters:
    joints:
      - pitch
      - turn
      - updown
      - leftjoint1
      - leftjoint2
      - leftjoint3
      - leftjoint4
      - leftjoint5
      - leftjoint6
      - rightjoint1
      - rightjoint2
      - rightjoint3
      - rightjoint4
      - rightjoint5
      - rightjoint6
    interface_name: position
