# Copyright (c) 2025 b»robotized group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ros2_control controllers for the dual six-axis arms.

controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    base_position_controller:
      type: forward_command_controller/ForwardCommandController

    left_arm_position_controller:
      type: forward_command_controller/ForwardCommandController

    right_arm_position_controller:
      type: forward_command_controller/ForwardCommandController

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    all_position_controller:
      type: forward_command_controller/ForwardCommandController

base_position_controller:
  ros__parameters:
    joints:
      - pitch
      - turn
      - updown
    interface_name: position

left_arm_position_controller:
  ros__parameters:
    joints:
      - leftjoint1
      - leftjoint2
      - leftjoint3
      - leftjoint4
      - leftjoint5
      - leftjoint6
    interface_name: position

right_arm_position_controller:
  ros__parameters:
    joints:
      - rightjoint1
      - rightjoint2
      - rightjoint3
      - rightjoint4
      - rightjoint5
      - rightjoint6
    interface_name: position

forward_velocity_controller:
  ros__parameters:
    joints:
      - left_back
      - left_forward
      - right_back
      - right_forward
    interface_name: velocity

all_position_controller:
  ros__parameters:
    joints:
      - pitch
      - turn
      - updown
      - leftjoint1
      - leftjoint2
      - leftjoint3
      - leftjoint4
      - leftjoint5
      - leftjoint6
      - rightjoint1
      - rightjoint2
      - rightjoint3
      - rightjoint4
      - rightjoint5
      - rightjoint6
    interface_name: position
