# 滑块测试配置 - current all-position controller.

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    slider_controller:
      type: forward_command_controller/ForwardCommandController

slider_controller:
  ros__parameters:
    joints:
      - pitch
      - turn
      - updown
      - leftjoint1
      - leftjoint2
      - leftjoint3
      - leftjoint4
      - leftjoint5
      - leftjoint6
      - rightjoint1
      - rightjoint2
      - rightjoint3
      - rightjoint4
      - rightjoint5
      - rightjoint6
    interface_name: position
