from moveit_configs_utils import MoveItConfigsBuilder
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, GroupAction, IncludeLaunchDescription
from launch.conditions import IfCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from moveit_configs_utils.launches import generate_move_group_launch
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue


DEFAULT_LOADED_POSE_FAMILY_DEG = "[0.0,-45.0,120.0,-75.0,0.0,0.0]"


def generate_launch_description():
    moveit_config = (
        MoveItConfigsBuilder("alfa_robot", package_name="alfa_robot_moveit_config")
        .to_moveit_configs()
    )

    declared_arguments = [
        DeclareLaunchArgument("execute", default_value="true"),
        DeclareLaunchArgument("execution_backend", default_value="moveit"),
        DeclareLaunchArgument(
            "execution_action_name",
            default_value="/dual_arm_trajectory_controller/follow_joint_trajectory",
        ),
        DeclareLaunchArgument("execution_action_wait_timeout_s", default_value="5.0"),
        DeclareLaunchArgument("execution_result_timeout_s", default_value="0.0"),
        DeclareLaunchArgument("execution_include_turn", default_value="true"),
        DeclareLaunchArgument("execution_allow_hold_missing_target_joints", default_value="true"),
        DeclareLaunchArgument("execution_reject_unmapped_planned_joints", default_value="true"),
        DeclareLaunchArgument("start_move_group", default_value="true"),
        DeclareLaunchArgument("box_front_x", default_value="0.625"),
        DeclareLaunchArgument("scene_y_shift", default_value="0.0"),
        DeclareLaunchArgument("fixed_updown", default_value="0.45"),
        DeclareLaunchArgument("world_to_base_z", default_value="0.202094"),
        DeclareLaunchArgument("top_suction_x_offset", default_value="0.15"),
        DeclareLaunchArgument("top_suction_z_offset", default_value="0.2"),
        DeclareLaunchArgument("max_rounds", default_value="10"),
        DeclareLaunchArgument("include_top_suction", default_value="true"),
        DeclareLaunchArgument("reject_ik_collisions", default_value="false"),
        DeclareLaunchArgument("check_goal_collision", default_value="false"),
        DeclareLaunchArgument("prefer_commanded_state", default_value="true"),
        DeclareLaunchArgument("allowed_start_tolerance", default_value="0.05"),
        DeclareLaunchArgument("ik_timeout", default_value="2.0"),
        DeclareLaunchArgument("planning_time", default_value="8.0"),
        DeclareLaunchArgument("planning_attempts", default_value="8"),
        DeclareLaunchArgument("velocity_scale", default_value="1.0"),
        DeclareLaunchArgument("acceleration_scale", default_value="1.0"),
        DeclareLaunchArgument("record_jsonl_path", default_value="/mnt/mydisk/ALFA/alfa_robot/data/ik_benchmark/moveit_box_stack_flow/moveit_box_stack_flow.jsonl"),
        DeclareLaunchArgument("record_trajectories", default_value="true"),
        DeclareLaunchArgument("extract_monitor_snapshot_path", default_value="/mnt/mydisk/ALFA/alfa_robot/data/ik_benchmark/extract_stage_monitor/latest_snapshot.json"),
        DeclareLaunchArgument("extract_monitor_top_suction", default_value="false"),
        DeclareLaunchArgument("ik_workers", default_value="1"),
        DeclareLaunchArgument("ik_h_candidate_count", default_value="64"),
        # updown(h) 候选采样范围：逻辑/URDF 与电机物理空间均为 [0, 0.7]。
        DeclareLaunchArgument("ik_h_lower", default_value="0.0"),
        DeclareLaunchArgument("ik_h_upper", default_value="0.7"),
        DeclareLaunchArgument("ik_h_step", default_value="0.01"),
        DeclareLaunchArgument("ik_full_h_range_scan", default_value="true"),
        DeclareLaunchArgument("ik_seed_count", default_value="32"),
        DeclareLaunchArgument("ik_candidate_timeout", default_value="0.01"),
        DeclareLaunchArgument("ik_h_search_margin", default_value="0.2"),
        DeclareLaunchArgument("ik_try_target_orders", default_value="false"),
        DeclareLaunchArgument("ik_use_reversed_target_order", default_value="true"),
        DeclareLaunchArgument("ik_loaded_family_distance_weight", default_value="0.2"),
        DeclareLaunchArgument("ik_loaded_preferred_distance_weight", default_value="0.1"),
        DeclareLaunchArgument("ik_updown_cost_enabled", default_value="false"),
        DeclareLaunchArgument("ik_joint_limit_margin_weight", default_value="1.0"),
        DeclareLaunchArgument("ik_joint1_limit_weight", default_value="0.5"),
        DeclareLaunchArgument("ik_joint2_limit_weight", default_value="3.0"),
        DeclareLaunchArgument("ik_joint3_limit_weight", default_value="0.7"),
        DeclareLaunchArgument("ik_joint4_limit_weight", default_value="0.5"),
        DeclareLaunchArgument("ik_joint5_limit_weight", default_value="1.5"),
        DeclareLaunchArgument("ik_joint6_limit_weight", default_value="1.2"),
        DeclareLaunchArgument("ik_joint_limit_free_ratio", default_value="0.6"),
        DeclareLaunchArgument("loaded_left_pose_family_deg", default_value=DEFAULT_LOADED_POSE_FAMILY_DEG),
        DeclareLaunchArgument("loaded_right_pose_family_deg", default_value=DEFAULT_LOADED_POSE_FAMILY_DEG),
        DeclareLaunchArgument("loaded_preferred_pose_index", default_value="0"),
        DeclareLaunchArgument("front_z_reach_lower", default_value="0.45"),
        DeclareLaunchArgument("front_z_reach_upper", default_value="1.25"),
        DeclareLaunchArgument("top_z_reach_lower", default_value="0.0"),
        DeclareLaunchArgument("top_z_reach_upper", default_value="0.6"),
        DeclareLaunchArgument("ik_top_position_tolerance", default_value="0.04"),
        DeclareLaunchArgument("ik_top_orientation_tolerance_deg", default_value="7.0"),
        DeclareLaunchArgument("optimized_ik_check_collision", default_value="true"),
        DeclareLaunchArgument("ik_fallback_enabled", default_value="false"),
        DeclareLaunchArgument("enable_container_obstacle", default_value="true"),
        DeclareLaunchArgument("container_frame", default_value="world"),
        DeclareLaunchArgument("container_track_vehicle_drift", default_value="false"),
        DeclareLaunchArgument("vehicle_drift_global_frame", default_value="map"),
        DeclareLaunchArgument("vehicle_drift_translation_threshold_m", default_value="0.05"),
        DeclareLaunchArgument("vehicle_drift_rotation_threshold_rad", default_value="0.02"),
        DeclareLaunchArgument("container_length", default_value="4.0"),
        DeclareLaunchArgument("container_width", default_value="1.8"),
        DeclareLaunchArgument("container_height", default_value="2.4"),
        DeclareLaunchArgument("container_center_x", default_value="0.8"),
        DeclareLaunchArgument("container_center_y", default_value="0.0"),
        DeclareLaunchArgument("container_pose_dynamic", default_value="false"),
        DeclareLaunchArgument("container_pose_map_x", default_value="0.8"),
        DeclareLaunchArgument("container_pose_map_y", default_value="0.0"),
        DeclareLaunchArgument("container_pose_map_yaw", default_value="0.0"),
        DeclareLaunchArgument("container_floor_z", default_value="0.0"),
        DeclareLaunchArgument("container_wall_thickness", default_value="0.02"),
        DeclareLaunchArgument("enable_attached_box_collision", default_value="true"),
        DeclareLaunchArgument("carried_box_depth", default_value="0.3"),
        DeclareLaunchArgument("carried_box_width", default_value="0.5"),
        DeclareLaunchArgument("carried_box_height", default_value="0.4"),
        DeclareLaunchArgument("carried_box_grasp_lateral_offset", default_value="0.10"),
        DeclareLaunchArgument("attached_box_collision_padding", default_value="-0.002"),
        DeclareLaunchArgument("enable_static_box_obstacles", default_value="true"),
        DeclareLaunchArgument("static_box_obstacle_inset", default_value="0.002"),
        DeclareLaunchArgument("extract_demo_left_box_id", default_value="1"),
        DeclareLaunchArgument("extract_demo_right_box_id", default_value="3"),
        DeclareLaunchArgument(
            "extract_demo_pair_sequence",
            default_value="1,3;4,6;7,9;10,12;13,15",
        ),
        DeclareLaunchArgument("extract_demo_all_rows", default_value="false"),
        DeclareLaunchArgument("extract_monitor_top_suction", default_value="false"),
        DeclareLaunchArgument("extract_monitor_left_top_suction", default_value="false"),
        DeclareLaunchArgument("extract_monitor_right_top_suction", default_value="false"),
        DeclareLaunchArgument("extract_step_x", default_value="0.03"),
        DeclareLaunchArgument("extract_max_x", default_value="0.36"),
        DeclareLaunchArgument("extract_neighbor_margin", default_value="0.02"),
        DeclareLaunchArgument("extract_fail_fast", default_value="false"),
        DeclareLaunchArgument("extract_success_extra_steps", default_value="3"),
        DeclareLaunchArgument("extract_position_tolerance", default_value="0.01"),
        DeclareLaunchArgument("extract_orientation_tolerance", default_value="0.05"),
        DeclareLaunchArgument("extract_max_tip_z_drop", default_value="0.002"),
        DeclareLaunchArgument("extract_min_tool_normal_z", default_value="-0.0001"),
        DeclareLaunchArgument("extract_score_lift_weight", default_value="10.0"),
        DeclareLaunchArgument("extract_score_pitch_weight", default_value="0.02"),
        DeclareLaunchArgument("extract_score_retreat_continuity_weight", default_value="0.2"),
        DeclareLaunchArgument("extract_score_joint_delta_weight", default_value="0.6"),
        DeclareLaunchArgument("extract_score_tip_position_delta_weight", default_value="2.0"),
        DeclareLaunchArgument("extract_score_tip_orientation_delta_weight", default_value="0.05"),
        DeclareLaunchArgument("extract_max_joint_delta", default_value="0.17453292519943295"),
        DeclareLaunchArgument("extract_demo_direct_grasp_start", default_value="false"),
        DeclareLaunchArgument("extract_grasp_ik_home_updown", default_value="0.3"),
        DeclareLaunchArgument("extract_monitor_turn", default_value="0.0"),
        DeclareLaunchArgument("extract_benchmark_all_legal_ik", default_value="false"),
        DeclareLaunchArgument("extract_benchmark_dual_arm", default_value="false"),
        DeclareLaunchArgument("extract_benchmark_dual_async", default_value="false"),
        DeclareLaunchArgument("extract_benchmark_record_rollouts", default_value="false"),
        DeclareLaunchArgument("extract_benchmark_candidate_limit", default_value="25"),
        DeclareLaunchArgument("extract_benchmark_extract_workers", default_value="1"),
        DeclareLaunchArgument("extract_benchmark_extract_success_quorum", default_value="3"),
        DeclareLaunchArgument("extract_benchmark_extract_quality_success_quorum", default_value="0"),
        DeclareLaunchArgument("extract_benchmark_extract_quality_loaded_distance_sum", default_value="0.0"),
        DeclareLaunchArgument("extract_ik_dedup_enabled", default_value="true"),
        DeclareLaunchArgument("extract_ik_dedup_joint_threshold_deg", default_value="1.0"),
        DeclareLaunchArgument("extract_ik_dedup_h_threshold", default_value="0.005"),
        DeclareLaunchArgument("extract_ik_stratified_limit_enabled", default_value="false"),
        DeclareLaunchArgument("extract_ik_stratified_h_bucket", default_value="0.05"),
        DeclareLaunchArgument("extract_ik_stratified_top_score_count", default_value="12"),
        DeclareLaunchArgument("extract_ik_candidate_reserve_limit", default_value="64"),
        DeclareLaunchArgument("extract_ik_candidate_reserve_stratified", default_value="true"),
        DeclareLaunchArgument("extract_ik_candidate_reserve_interleave_stride", default_value="4"),
        DeclareLaunchArgument("extract_ik_loaded_distance_order_weight", default_value="0.0"),
        DeclareLaunchArgument("extract_monitor_capture_raw_ik", default_value="false"),
        DeclareLaunchArgument("extract_monitor_build_final_replay", default_value="true"),
        DeclareLaunchArgument("extract_monitor_place_cycle_enabled", default_value="false"),
        DeclareLaunchArgument("extract_monitor_place_updown", default_value="0.10"),
        DeclareLaunchArgument("extract_monitor_place_transition_updown", default_value="0.10"),
        DeclareLaunchArgument(
            "extract_monitor_place_left_pose_deg",
            default_value="[0.0,-55.0,-50.0,-60.0,0.0,0.0]",
        ),
        DeclareLaunchArgument(
            "extract_monitor_place_right_pose_deg",
            default_value="[0.0,-55.0,-50.0,-60.0,0.0,0.0]",
        ),
        DeclareLaunchArgument("extract_rollout_mode", default_value="greedy"),
        DeclareLaunchArgument("extract_rrt_rollout_enabled", default_value="false"),
        DeclareLaunchArgument("extract_box_pose_rrt_max_iterations", default_value="160"),
        DeclareLaunchArgument("extract_box_pose_rrt_paths_per_arm", default_value="8"),
        DeclareLaunchArgument("extract_box_pose_rrt_path_pair_limit", default_value="64"),
        DeclareLaunchArgument("extract_box_pose_rrt_max_retreat", default_value="0.55"),
        DeclareLaunchArgument("extract_box_pose_rrt_max_lift", default_value="0.55"),
        DeclareLaunchArgument("extract_box_pose_rrt_separation_margin", default_value="0.03"),
        DeclareLaunchArgument("extract_box_pose_rrt_analytic_root_samples", default_value="12"),
        DeclareLaunchArgument("extract_box_pose_rrt_diagnostics", default_value="false"),
        DeclareLaunchArgument("extract_box_pose_rrt_edge_scene_collision", default_value="true"),
        DeclareLaunchArgument("extract_box_pose_rrt_parent_candidates", default_value="8"),
        DeclareLaunchArgument("extract_box_pose_rrt_parent_diverse_candidates", default_value="0"),
        DeclareLaunchArgument("extract_box_pose_rrt_parent_endpoint_score_weight", default_value="0.05"),
        DeclareLaunchArgument("extract_box_pose_rrt_parent_node_score_weight", default_value="0.0"),
        DeclareLaunchArgument("extract_box_pose_rrt_parent_density_weight", default_value="0.0"),
        DeclareLaunchArgument("extract_box_pose_rrt_max_lateral", default_value="0.0"),
        DeclareLaunchArgument("extract_box_pose_rrt_step_lateral", default_value="0.02"),
        DeclareLaunchArgument("extract_box_pose_rrt_front_free_motion", default_value="true"),
        DeclareLaunchArgument("extract_box_pose_rrt_front_goal_requires_max_pitch", default_value="false"),
        DeclareLaunchArgument("extract_box_pose_rrt_best_first_fallback", default_value="true"),
        DeclareLaunchArgument("extract_box_pose_rrt_best_first_first", default_value="false"),
        DeclareLaunchArgument("extract_box_pose_rrt_top_best_first_first", default_value="false"),
        DeclareLaunchArgument("extract_box_pose_rrt_top_goal_min_pitch_deg", default_value="5.0"),
        DeclareLaunchArgument("extract_box_pose_rrt_best_first_max_expansions", default_value="800"),
        DeclareLaunchArgument("extract_box_pose_rrt_best_first_heuristic_weight", default_value="1.0"),
        DeclareLaunchArgument("extract_rrt_planning_group", default_value="dual_arm"),
        DeclareLaunchArgument("extract_rrt_planning_time", default_value="0.35"),
        DeclareLaunchArgument("extract_rrt_planning_attempts", default_value="1"),
        DeclareLaunchArgument("extract_rrt_endpoint_per_arm_limit", default_value="8"),
        DeclareLaunchArgument("extract_rrt_goal_limit", default_value="8"),
        DeclareLaunchArgument("extract_benchmark_plan_loaded_after_success", default_value="false"),
        DeclareLaunchArgument("extract_loaded_planning_group", default_value="dual_arm_with_base"),
        DeclareLaunchArgument("extract_loaded_planner_id", default_value=""),
        DeclareLaunchArgument("extract_loaded_planning_time", default_value="1.0"),
        DeclareLaunchArgument("extract_loaded_planning_attempts", default_value="8"),
        DeclareLaunchArgument("extract_loaded_use_direct_pipeline", default_value="false"),
        DeclareLaunchArgument("extract_loaded_planning_mode", default_value="rrt"),
        DeclareLaunchArgument("extract_loaded_parallel_workers", default_value="1"),
        DeclareLaunchArgument("extract_loaded_candidate_limit", default_value="0"),
        DeclareLaunchArgument("extract_loaded_sort_by_pose_distance", default_value="false"),
        DeclareLaunchArgument("extract_loaded_stop_on_first_success", default_value="true"),
        DeclareLaunchArgument("extract_loaded_target_updown", default_value="0.3"),
        DeclareLaunchArgument("extract_loaded_lateral_shift_enabled", default_value="false"),
        DeclareLaunchArgument("extract_loaded_lateral_shift_distance", default_value="0.4"),
        DeclareLaunchArgument("extract_loaded_lateral_shift_step", default_value="0.0"),
        DeclareLaunchArgument("extract_loaded_lateral_shift_column", default_value="2"),
        DeclareLaunchArgument("extract_loaded_pre_lower_left_box_id", default_value="0"),
        DeclareLaunchArgument("extract_loaded_pre_lower_right_box_id", default_value="0"),
        DeclareLaunchArgument("extract_loaded_pre_lower_updown_delta", default_value="0.0"),
        DeclareLaunchArgument("enforce_loaded_plan_aabb_clearance", default_value="false"),
        DeclareLaunchArgument("enforce_loaded_static_box_wall_aabb_clearance", default_value="true"),
        DeclareLaunchArgument("record_tip_error_ik_candidates", default_value="false"),
        DeclareLaunchArgument("record_tip_error_ik_candidate_limit", default_value="80"),
        DeclareLaunchArgument(
            "extract_benchmark_csv_path",
            default_value="/mnt/mydisk/ALFA/alfa_robot/data/ik_benchmark/motion51_extract_replay/extract_all_legal_ik_timing.csv",
        ),
    ]

    # MoveIt defaults to 0.01 rad start-state tolerance. The ros2_control mock
    # controller can finish a trajectory with tiny spline residuals slightly
    # above that, causing the next execute() to abort even though the robot is
    # effectively at the previous target.
    moveit_config.trajectory_execution["trajectory_execution.allowed_start_tolerance"] = ParameterValue(
        LaunchConfiguration("allowed_start_tolerance"), value_type=float
    )

    dual_arm_planner = Node(
        package="alfa_robot_moveit_config",
        executable="dual_arm_planner_node",
        name="dual_arm_planner",
        output="screen",
        parameters=[
            moveit_config.robot_description,
            moveit_config.robot_description_semantic,
            moveit_config.robot_description_kinematics,
            moveit_config.planning_pipelines,
            moveit_config.joint_limits,
            {
                "execute": ParameterValue(LaunchConfiguration("execute"), value_type=bool),
                "execution_backend": LaunchConfiguration("execution_backend"),
                "execution_action_name": LaunchConfiguration("execution_action_name"),
                "execution_action_wait_timeout_s": ParameterValue(LaunchConfiguration("execution_action_wait_timeout_s"), value_type=float),
                "execution_result_timeout_s": ParameterValue(LaunchConfiguration("execution_result_timeout_s"), value_type=float),
                "execution_include_turn": ParameterValue(LaunchConfiguration("execution_include_turn"), value_type=bool),
                "execution_allow_hold_missing_target_joints": ParameterValue(LaunchConfiguration("execution_allow_hold_missing_target_joints"), value_type=bool),
                "execution_reject_unmapped_planned_joints": ParameterValue(LaunchConfiguration("execution_reject_unmapped_planned_joints"), value_type=bool),
                "box_front_x": ParameterValue(LaunchConfiguration("box_front_x"), value_type=float),
                "scene_y_shift": ParameterValue(LaunchConfiguration("scene_y_shift"), value_type=float),
                "fixed_updown": ParameterValue(LaunchConfiguration("fixed_updown"), value_type=float),
                "world_to_base_z": ParameterValue(LaunchConfiguration("world_to_base_z"), value_type=float),
                "top_suction_x_offset": ParameterValue(LaunchConfiguration("top_suction_x_offset"), value_type=float),
                "top_suction_z_offset": ParameterValue(LaunchConfiguration("top_suction_z_offset"), value_type=float),
                "max_rounds": ParameterValue(LaunchConfiguration("max_rounds"), value_type=int),
                "include_top_suction": ParameterValue(LaunchConfiguration("include_top_suction"), value_type=bool),
                "reject_ik_collisions": ParameterValue(LaunchConfiguration("reject_ik_collisions"), value_type=bool),
                "check_goal_collision": ParameterValue(LaunchConfiguration("check_goal_collision"), value_type=bool),
                "prefer_commanded_state": ParameterValue(LaunchConfiguration("prefer_commanded_state"), value_type=bool),
                "ik_timeout": ParameterValue(LaunchConfiguration("ik_timeout"), value_type=float),
                "planning_time": ParameterValue(LaunchConfiguration("planning_time"), value_type=float),
                "planning_attempts": ParameterValue(LaunchConfiguration("planning_attempts"), value_type=int),
                "velocity_scale": ParameterValue(LaunchConfiguration("velocity_scale"), value_type=float),
                "acceleration_scale": ParameterValue(LaunchConfiguration("acceleration_scale"), value_type=float),
                "record_jsonl_path": LaunchConfiguration("record_jsonl_path"),
                "record_trajectories": ParameterValue(LaunchConfiguration("record_trajectories"), value_type=bool),
                "extract_monitor_snapshot_path": LaunchConfiguration("extract_monitor_snapshot_path"),
                "extract_monitor_top_suction": ParameterValue(LaunchConfiguration("extract_monitor_top_suction"), value_type=bool),
                "ik_workers": ParameterValue(LaunchConfiguration("ik_workers"), value_type=int),
                "ik_h_candidate_count": ParameterValue(LaunchConfiguration("ik_h_candidate_count"), value_type=int),
                "ik_h_lower": ParameterValue(LaunchConfiguration("ik_h_lower"), value_type=float),
                "ik_h_upper": ParameterValue(LaunchConfiguration("ik_h_upper"), value_type=float),
                "ik_h_step": ParameterValue(LaunchConfiguration("ik_h_step"), value_type=float),
                "ik_full_h_range_scan": ParameterValue(LaunchConfiguration("ik_full_h_range_scan"), value_type=bool),
                "ik_seed_count": ParameterValue(LaunchConfiguration("ik_seed_count"), value_type=int),
                "ik_candidate_timeout": ParameterValue(LaunchConfiguration("ik_candidate_timeout"), value_type=float),
                "ik_h_search_margin": ParameterValue(LaunchConfiguration("ik_h_search_margin"), value_type=float),
                "ik_h_step": ParameterValue(LaunchConfiguration("ik_h_step"), value_type=float),
                "ik_try_target_orders": ParameterValue(LaunchConfiguration("ik_try_target_orders"), value_type=bool),
                "ik_use_reversed_target_order": ParameterValue(LaunchConfiguration("ik_use_reversed_target_order"), value_type=bool),
                "ik_loaded_family_distance_weight": ParameterValue(LaunchConfiguration("ik_loaded_family_distance_weight"), value_type=float),
                "ik_loaded_preferred_distance_weight": ParameterValue(LaunchConfiguration("ik_loaded_preferred_distance_weight"), value_type=float),
                "ik_updown_cost_enabled": ParameterValue(LaunchConfiguration("ik_updown_cost_enabled"), value_type=bool),
                "ik_joint_limit_margin_weight": ParameterValue(LaunchConfiguration("ik_joint_limit_margin_weight"), value_type=float),
                "ik_joint1_limit_weight": ParameterValue(LaunchConfiguration("ik_joint1_limit_weight"), value_type=float),
                "ik_joint2_limit_weight": ParameterValue(LaunchConfiguration("ik_joint2_limit_weight"), value_type=float),
                "ik_joint3_limit_weight": ParameterValue(LaunchConfiguration("ik_joint3_limit_weight"), value_type=float),
                "ik_joint4_limit_weight": ParameterValue(LaunchConfiguration("ik_joint4_limit_weight"), value_type=float),
                "ik_joint5_limit_weight": ParameterValue(LaunchConfiguration("ik_joint5_limit_weight"), value_type=float),
                "ik_joint6_limit_weight": ParameterValue(LaunchConfiguration("ik_joint6_limit_weight"), value_type=float),
                "ik_joint_limit_free_ratio": ParameterValue(LaunchConfiguration("ik_joint_limit_free_ratio"), value_type=float),
                "loaded_left_pose_family_deg": ParameterValue(LaunchConfiguration("loaded_left_pose_family_deg"), value_type=str),
                "loaded_right_pose_family_deg": ParameterValue(LaunchConfiguration("loaded_right_pose_family_deg"), value_type=str),
                "loaded_preferred_pose_index": ParameterValue(LaunchConfiguration("loaded_preferred_pose_index"), value_type=int),
                "front_z_reach_lower": ParameterValue(LaunchConfiguration("front_z_reach_lower"), value_type=float),
                "front_z_reach_upper": ParameterValue(LaunchConfiguration("front_z_reach_upper"), value_type=float),
                "top_z_reach_lower": ParameterValue(LaunchConfiguration("top_z_reach_lower"), value_type=float),
                "top_z_reach_upper": ParameterValue(LaunchConfiguration("top_z_reach_upper"), value_type=float),
                "ik_top_position_tolerance": ParameterValue(LaunchConfiguration("ik_top_position_tolerance"), value_type=float),
                "ik_top_orientation_tolerance_deg": ParameterValue(LaunchConfiguration("ik_top_orientation_tolerance_deg"), value_type=float),
                "optimized_ik_check_collision": ParameterValue(LaunchConfiguration("optimized_ik_check_collision"), value_type=bool),
                "ik_fallback_enabled": ParameterValue(LaunchConfiguration("ik_fallback_enabled"), value_type=bool),
                "enable_container_obstacle": ParameterValue(LaunchConfiguration("enable_container_obstacle"), value_type=bool),
                "container_frame": LaunchConfiguration("container_frame"),
                "container_track_vehicle_drift": ParameterValue(LaunchConfiguration("container_track_vehicle_drift"), value_type=bool),
                "vehicle_drift_global_frame": LaunchConfiguration("vehicle_drift_global_frame"),
                "vehicle_drift_translation_threshold_m": ParameterValue(LaunchConfiguration("vehicle_drift_translation_threshold_m"), value_type=float),
                "vehicle_drift_rotation_threshold_rad": ParameterValue(LaunchConfiguration("vehicle_drift_rotation_threshold_rad"), value_type=float),
                "container_length": ParameterValue(LaunchConfiguration("container_length"), value_type=float),
                "container_width": ParameterValue(LaunchConfiguration("container_width"), value_type=float),
                "container_height": ParameterValue(LaunchConfiguration("container_height"), value_type=float),
                "container_center_x": ParameterValue(LaunchConfiguration("container_center_x"), value_type=float),
                "container_center_y": ParameterValue(LaunchConfiguration("container_center_y"), value_type=float),
                "container_pose_dynamic": ParameterValue(LaunchConfiguration("container_pose_dynamic"), value_type=bool),
                "container_pose_map_x": ParameterValue(LaunchConfiguration("container_pose_map_x"), value_type=float),
                "container_pose_map_y": ParameterValue(LaunchConfiguration("container_pose_map_y"), value_type=float),
                "container_pose_map_yaw": ParameterValue(LaunchConfiguration("container_pose_map_yaw"), value_type=float),
                "container_floor_z": ParameterValue(LaunchConfiguration("container_floor_z"), value_type=float),
                "container_wall_thickness": ParameterValue(LaunchConfiguration("container_wall_thickness"), value_type=float),
                "enable_attached_box_collision": ParameterValue(LaunchConfiguration("enable_attached_box_collision"), value_type=bool),
                "carried_box_depth": ParameterValue(LaunchConfiguration("carried_box_depth"), value_type=float),
                "carried_box_width": ParameterValue(LaunchConfiguration("carried_box_width"), value_type=float),
                "carried_box_height": ParameterValue(LaunchConfiguration("carried_box_height"), value_type=float),
                "carried_box_grasp_lateral_offset": ParameterValue(
                    LaunchConfiguration("carried_box_grasp_lateral_offset"), value_type=float
                ),
                "attached_box_collision_padding": ParameterValue(LaunchConfiguration("attached_box_collision_padding"), value_type=float),
                "enable_static_box_obstacles": ParameterValue(LaunchConfiguration("enable_static_box_obstacles"), value_type=bool),
                "static_box_obstacle_inset": ParameterValue(LaunchConfiguration("static_box_obstacle_inset"), value_type=float),
                "extract_demo_left_box_id": ParameterValue(LaunchConfiguration("extract_demo_left_box_id"), value_type=int),
                "extract_demo_right_box_id": ParameterValue(LaunchConfiguration("extract_demo_right_box_id"), value_type=int),
                "extract_demo_pair_sequence": ParameterValue(LaunchConfiguration("extract_demo_pair_sequence"), value_type=str),
                "extract_demo_all_rows": ParameterValue(LaunchConfiguration("extract_demo_all_rows"), value_type=bool),
                "extract_monitor_top_suction": ParameterValue(LaunchConfiguration("extract_monitor_top_suction"), value_type=bool),
                "extract_monitor_left_top_suction": ParameterValue(LaunchConfiguration("extract_monitor_left_top_suction"), value_type=bool),
                "extract_monitor_right_top_suction": ParameterValue(LaunchConfiguration("extract_monitor_right_top_suction"), value_type=bool),
                "extract_step_x": ParameterValue(LaunchConfiguration("extract_step_x"), value_type=float),
                "extract_max_x": ParameterValue(LaunchConfiguration("extract_max_x"), value_type=float),
                "extract_neighbor_margin": ParameterValue(LaunchConfiguration("extract_neighbor_margin"), value_type=float),
                "extract_fail_fast": ParameterValue(LaunchConfiguration("extract_fail_fast"), value_type=bool),
                "extract_success_extra_steps": ParameterValue(LaunchConfiguration("extract_success_extra_steps"), value_type=int),
                "extract_position_tolerance": ParameterValue(LaunchConfiguration("extract_position_tolerance"), value_type=float),
                "extract_orientation_tolerance": ParameterValue(LaunchConfiguration("extract_orientation_tolerance"), value_type=float),
                "extract_max_tip_z_drop": ParameterValue(LaunchConfiguration("extract_max_tip_z_drop"), value_type=float),
                "extract_min_tool_normal_z": ParameterValue(LaunchConfiguration("extract_min_tool_normal_z"), value_type=float),
                "extract_score_lift_weight": ParameterValue(LaunchConfiguration("extract_score_lift_weight"), value_type=float),
                "extract_score_pitch_weight": ParameterValue(LaunchConfiguration("extract_score_pitch_weight"), value_type=float),
                "extract_score_retreat_continuity_weight": ParameterValue(LaunchConfiguration("extract_score_retreat_continuity_weight"), value_type=float),
                "extract_score_joint_delta_weight": ParameterValue(LaunchConfiguration("extract_score_joint_delta_weight"), value_type=float),
                "extract_score_tip_position_delta_weight": ParameterValue(LaunchConfiguration("extract_score_tip_position_delta_weight"), value_type=float),
                "extract_score_tip_orientation_delta_weight": ParameterValue(LaunchConfiguration("extract_score_tip_orientation_delta_weight"), value_type=float),
                "extract_max_joint_delta": ParameterValue(LaunchConfiguration("extract_max_joint_delta"), value_type=float),
                "extract_demo_direct_grasp_start": ParameterValue(LaunchConfiguration("extract_demo_direct_grasp_start"), value_type=bool),
                "extract_grasp_ik_home_updown": ParameterValue(LaunchConfiguration("extract_grasp_ik_home_updown"), value_type=float),
                "extract_monitor_turn": ParameterValue(LaunchConfiguration("extract_monitor_turn"), value_type=float),
                "extract_benchmark_all_legal_ik": ParameterValue(LaunchConfiguration("extract_benchmark_all_legal_ik"), value_type=bool),
                "extract_benchmark_dual_arm": ParameterValue(LaunchConfiguration("extract_benchmark_dual_arm"), value_type=bool),
                "extract_benchmark_dual_async": ParameterValue(LaunchConfiguration("extract_benchmark_dual_async"), value_type=bool),
                "extract_benchmark_record_rollouts": ParameterValue(LaunchConfiguration("extract_benchmark_record_rollouts"), value_type=bool),
                "extract_benchmark_candidate_limit": ParameterValue(LaunchConfiguration("extract_benchmark_candidate_limit"), value_type=int),
                "extract_benchmark_extract_workers": ParameterValue(LaunchConfiguration("extract_benchmark_extract_workers"), value_type=int),
                "extract_benchmark_extract_success_quorum": ParameterValue(LaunchConfiguration("extract_benchmark_extract_success_quorum"), value_type=int),
                "extract_benchmark_extract_quality_success_quorum": ParameterValue(LaunchConfiguration("extract_benchmark_extract_quality_success_quorum"), value_type=int),
                "extract_benchmark_extract_quality_loaded_distance_sum": ParameterValue(LaunchConfiguration("extract_benchmark_extract_quality_loaded_distance_sum"), value_type=float),
                "extract_ik_dedup_enabled": ParameterValue(LaunchConfiguration("extract_ik_dedup_enabled"), value_type=bool),
                "extract_ik_dedup_joint_threshold_deg": ParameterValue(LaunchConfiguration("extract_ik_dedup_joint_threshold_deg"), value_type=float),
                "extract_ik_dedup_h_threshold": ParameterValue(LaunchConfiguration("extract_ik_dedup_h_threshold"), value_type=float),
                "extract_ik_stratified_limit_enabled": ParameterValue(LaunchConfiguration("extract_ik_stratified_limit_enabled"), value_type=bool),
                "extract_ik_stratified_h_bucket": ParameterValue(LaunchConfiguration("extract_ik_stratified_h_bucket"), value_type=float),
                "extract_ik_stratified_top_score_count": ParameterValue(LaunchConfiguration("extract_ik_stratified_top_score_count"), value_type=int),
                "extract_ik_candidate_reserve_limit": ParameterValue(LaunchConfiguration("extract_ik_candidate_reserve_limit"), value_type=int),
                "extract_ik_candidate_reserve_stratified": ParameterValue(LaunchConfiguration("extract_ik_candidate_reserve_stratified"), value_type=bool),
                "extract_ik_candidate_reserve_interleave_stride": ParameterValue(LaunchConfiguration("extract_ik_candidate_reserve_interleave_stride"), value_type=int),
                "extract_ik_loaded_distance_order_weight": ParameterValue(LaunchConfiguration("extract_ik_loaded_distance_order_weight"), value_type=float),
                "extract_monitor_capture_raw_ik": ParameterValue(LaunchConfiguration("extract_monitor_capture_raw_ik"), value_type=bool),
                "extract_monitor_build_final_replay": ParameterValue(LaunchConfiguration("extract_monitor_build_final_replay"), value_type=bool),
                "extract_monitor_place_cycle_enabled": ParameterValue(LaunchConfiguration("extract_monitor_place_cycle_enabled"), value_type=bool),
                "extract_monitor_place_updown": ParameterValue(LaunchConfiguration("extract_monitor_place_updown"), value_type=float),
                "extract_monitor_place_transition_updown": ParameterValue(LaunchConfiguration("extract_monitor_place_transition_updown"), value_type=float),
                "extract_monitor_place_left_pose_deg": ParameterValue(LaunchConfiguration("extract_monitor_place_left_pose_deg"), value_type=str),
                "extract_monitor_place_right_pose_deg": ParameterValue(LaunchConfiguration("extract_monitor_place_right_pose_deg"), value_type=str),
                "extract_rollout_mode": ParameterValue(LaunchConfiguration("extract_rollout_mode"), value_type=str),
                "extract_rrt_rollout_enabled": ParameterValue(LaunchConfiguration("extract_rrt_rollout_enabled"), value_type=bool),
                "extract_box_pose_rrt_max_iterations": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_max_iterations"), value_type=int),
                "extract_box_pose_rrt_paths_per_arm": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_paths_per_arm"), value_type=int),
                "extract_box_pose_rrt_path_pair_limit": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_path_pair_limit"), value_type=int),
                "extract_box_pose_rrt_max_retreat": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_max_retreat"), value_type=float),
                "extract_box_pose_rrt_max_lift": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_max_lift"), value_type=float),
                "extract_box_pose_rrt_separation_margin": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_separation_margin"), value_type=float),
                "extract_box_pose_rrt_analytic_root_samples": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_analytic_root_samples"), value_type=int),
                "extract_box_pose_rrt_diagnostics": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_diagnostics"), value_type=bool),
                "extract_box_pose_rrt_edge_scene_collision": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_edge_scene_collision"), value_type=bool),
                "extract_box_pose_rrt_parent_candidates": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_parent_candidates"), value_type=int),
                "extract_box_pose_rrt_parent_diverse_candidates": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_parent_diverse_candidates"), value_type=int),
                "extract_box_pose_rrt_parent_endpoint_score_weight": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_parent_endpoint_score_weight"), value_type=float),
                "extract_box_pose_rrt_parent_node_score_weight": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_parent_node_score_weight"), value_type=float),
                "extract_box_pose_rrt_parent_density_weight": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_parent_density_weight"), value_type=float),
                "extract_box_pose_rrt_max_lateral": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_max_lateral"), value_type=float),
                "extract_box_pose_rrt_step_lateral": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_step_lateral"), value_type=float),
                "extract_box_pose_rrt_front_free_motion": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_front_free_motion"), value_type=bool),
                "extract_box_pose_rrt_front_goal_requires_max_pitch": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_front_goal_requires_max_pitch"), value_type=bool),
                "extract_box_pose_rrt_best_first_fallback": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_best_first_fallback"), value_type=bool),
                "extract_box_pose_rrt_best_first_first": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_best_first_first"), value_type=bool),
                "extract_box_pose_rrt_top_best_first_first": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_top_best_first_first"), value_type=bool),
                "extract_box_pose_rrt_top_goal_min_pitch_deg": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_top_goal_min_pitch_deg"), value_type=float),
                "extract_box_pose_rrt_best_first_max_expansions": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_best_first_max_expansions"), value_type=int),
                "extract_box_pose_rrt_best_first_heuristic_weight": ParameterValue(LaunchConfiguration("extract_box_pose_rrt_best_first_heuristic_weight"), value_type=float),
                "extract_rrt_planning_group": LaunchConfiguration("extract_rrt_planning_group"),
                "extract_rrt_planning_time": ParameterValue(LaunchConfiguration("extract_rrt_planning_time"), value_type=float),
                "extract_rrt_planning_attempts": ParameterValue(LaunchConfiguration("extract_rrt_planning_attempts"), value_type=int),
                "extract_rrt_endpoint_per_arm_limit": ParameterValue(LaunchConfiguration("extract_rrt_endpoint_per_arm_limit"), value_type=int),
                "extract_rrt_goal_limit": ParameterValue(LaunchConfiguration("extract_rrt_goal_limit"), value_type=int),
                "extract_benchmark_plan_loaded_after_success": ParameterValue(LaunchConfiguration("extract_benchmark_plan_loaded_after_success"), value_type=bool),
                "extract_loaded_planning_group": LaunchConfiguration("extract_loaded_planning_group"),
                "extract_loaded_planner_id": ParameterValue(LaunchConfiguration("extract_loaded_planner_id"), value_type=str),
                "extract_loaded_planning_time": ParameterValue(LaunchConfiguration("extract_loaded_planning_time"), value_type=float),
                "extract_loaded_planning_attempts": ParameterValue(LaunchConfiguration("extract_loaded_planning_attempts"), value_type=int),
                "extract_loaded_use_direct_pipeline": ParameterValue(LaunchConfiguration("extract_loaded_use_direct_pipeline"), value_type=bool),
                "extract_loaded_planning_mode": ParameterValue(LaunchConfiguration("extract_loaded_planning_mode"), value_type=str),
                "extract_loaded_parallel_workers": ParameterValue(LaunchConfiguration("extract_loaded_parallel_workers"), value_type=int),
                "extract_loaded_candidate_limit": ParameterValue(LaunchConfiguration("extract_loaded_candidate_limit"), value_type=int),
                "extract_loaded_sort_by_pose_distance": ParameterValue(LaunchConfiguration("extract_loaded_sort_by_pose_distance"), value_type=bool),
                "extract_loaded_stop_on_first_success": ParameterValue(LaunchConfiguration("extract_loaded_stop_on_first_success"), value_type=bool),
                "extract_loaded_target_updown": ParameterValue(LaunchConfiguration("extract_loaded_target_updown"), value_type=float),
                "extract_loaded_lateral_shift_enabled": ParameterValue(LaunchConfiguration("extract_loaded_lateral_shift_enabled"), value_type=bool),
                "extract_loaded_lateral_shift_distance": ParameterValue(LaunchConfiguration("extract_loaded_lateral_shift_distance"), value_type=float),
                "extract_loaded_lateral_shift_step": ParameterValue(LaunchConfiguration("extract_loaded_lateral_shift_step"), value_type=float),
                "extract_loaded_lateral_shift_column": ParameterValue(LaunchConfiguration("extract_loaded_lateral_shift_column"), value_type=int),
                "extract_loaded_pre_lower_left_box_id": ParameterValue(LaunchConfiguration("extract_loaded_pre_lower_left_box_id"), value_type=int),
                "extract_loaded_pre_lower_right_box_id": ParameterValue(LaunchConfiguration("extract_loaded_pre_lower_right_box_id"), value_type=int),
                "extract_loaded_pre_lower_updown_delta": ParameterValue(LaunchConfiguration("extract_loaded_pre_lower_updown_delta"), value_type=float),
                "enforce_loaded_plan_aabb_clearance": ParameterValue(LaunchConfiguration("enforce_loaded_plan_aabb_clearance"), value_type=bool),
                "enforce_loaded_static_box_wall_aabb_clearance": ParameterValue(LaunchConfiguration("enforce_loaded_static_box_wall_aabb_clearance"), value_type=bool),
                "record_tip_error_ik_candidates": ParameterValue(LaunchConfiguration("record_tip_error_ik_candidates"), value_type=bool),
                "record_tip_error_ik_candidate_limit": ParameterValue(LaunchConfiguration("record_tip_error_ik_candidate_limit"), value_type=int),
                "extract_benchmark_csv_path": LaunchConfiguration("extract_benchmark_csv_path"),
            },
        ],
    )

    move_group_launch = generate_move_group_launch(moveit_config)
    launch_dir = moveit_config.package_path / "launch"
    support_nodes = [
        # static_virtual_joint_tfs.launch.py 故意不启动：它是 MoveIt 根据 SRDF virtual_joint
        # 自动生成的 identity（Z=0）world->base_link 静态发布者，会与 rsp.launch.py（robot_state_publisher
        # 按 URDF 发布，Z=0.202094）竞争同一条 TF 边，谁生效取决于启动时序。robot_state_publisher
        # 是唯一权威来源，这里保留 rsp.launch.py 即可。
        IncludeLaunchDescription(PythonLaunchDescriptionSource(str(launch_dir / "rsp.launch.py"))),
        Node(
            package="controller_manager",
            executable="ros2_control_node",
            parameters=[
                moveit_config.robot_description,
                str(moveit_config.package_path / "config/ros2_controllers.yaml"),
            ],
            output="screen",
        ),
        IncludeLaunchDescription(PythonLaunchDescriptionSource(str(launch_dir / "spawn_controllers.launch.py"))),
    ]
    move_group_stack = GroupAction(
        actions=move_group_launch.entities + support_nodes,
        condition=IfCondition(LaunchConfiguration("start_move_group")),
    )

    return LaunchDescription(declared_arguments + [move_group_stack, dual_arm_planner])
