# V3.1.1 MoveIt mock demo home. Updown -0.5m is physical mid-travel.
initial_positions:
  rear_suspension_joint: 0.085
  front_left_steering_joint: 0.0
  front_left_wheel_joint: 0.0
  front_right_steering_joint: 0.0
  front_right_wheel_joint: 0.0
  rear_left_steering_joint: 0.0
  rear_left_wheel_joint: 0.0
  rear_right_steering_joint: 0.0
  rear_right_wheel_joint: 0.0
  updown: -0.5
  head_joint: 0.0
  left_joint1: 2.61799387799
  left_joint2: 1.57079632679
  left_joint3: -0.0872664625997
  left_joint4: 2.09439510239
  left_joint5: 0.0
  left_joint6: 0.0
  left_joint7: 0.0
  left_hand_joint: 0.0
  right_joint1: -2.61799387799
  right_joint2: -1.57079632679
  right_joint3: 0.0872664625997
  right_joint4: -2.09439510239
  right_joint5: 0.0
  right_joint6: 0.0
  right_joint7: 0.0
  right_hand_joint: 0.0
