joint_limits:
  updown: {has_position_limits: true, min_position: -1.0, max_position: 0.0, has_velocity_limits: true, max_velocity: 0.15, has_acceleration_limits: true, max_acceleration: 0.15}
  head_joint: &head_joint {has_position_limits: true, min_position: -1.57, max_position: 1.57, has_velocity_limits: true, max_velocity: 1.0, has_acceleration_limits: true, max_acceleration: 1.0}
  head_pitch_joint: *head_joint
  left_joint1: &joint_180 {has_position_limits: true, min_position: -3.14159265, max_position: 3.14159265, has_velocity_limits: true, max_velocity: 1.0, has_acceleration_limits: true, max_acceleration: 1.0}
  left_joint2: &joint_105 {has_position_limits: true, min_position: -1.8325957145940461, max_position: 1.8325957145940461, has_velocity_limits: true, max_velocity: 1.0, has_acceleration_limits: true, max_acceleration: 1.0}
  left_joint3: *joint_180
  left_joint4: &joint_145 {has_position_limits: true, min_position: -2.53072742, max_position: 2.53072742, has_velocity_limits: true, max_velocity: 1.0, has_acceleration_limits: true, max_acceleration: 1.0}
  left_joint5: *joint_180
  left_joint6: &joint_110 {has_position_limits: true, min_position: -1.91986218, max_position: 1.91986218, has_velocity_limits: true, max_velocity: 1.0, has_acceleration_limits: true, max_acceleration: 1.0}
  left_joint7: *joint_180
  right_joint1: *joint_180
  right_joint2: *joint_105
  right_joint3: *joint_180
  right_joint4: *joint_145
  right_joint5: *joint_180
  right_joint6: *joint_110
  right_joint7: *joint_180
  active_suspension_joint: {has_position_limits: true, min_position: -0.15, max_position: 0.0, has_velocity_limits: true, max_velocity: 1.0, has_acceleration_limits: false}
  caster01_joint: &chassis_joint {has_position_limits: true, min_position: -3.14159, max_position: 3.14159, has_velocity_limits: true, max_velocity: 1.0, has_acceleration_limits: false}
  wheel01_joint: *chassis_joint
  caster02_joint: *chassis_joint
  wheel02_joint: *chassis_joint
  caster03_joint: *chassis_joint
  wheel03_joint: *chassis_joint
  caster04_joint: *chassis_joint
  wheel04_joint: *chassis_joint
