# MoveIt controller management - 双控制器

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - torso_controller
    - dual_arm_controller

  torso_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - pitch
      - turn

  dual_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - updown
      - leftjoint1
      - leftjoint2
      - leftjoint3
      - leftjoint4
      - leftjoint5
      - leftjoint6
      - rightjoint1
      - rightjoint2
      - rightjoint3
      - rightjoint4
      - rightjoint5
      - rightjoint6
